### PR TITLE
Add CD config

### PR DESCRIPTION
**Pull request by pselle**

### CODE REVIEW

**Comment by pselle** [comment]
cc @ewindisch

**Comment by ewindisch** [comment]
Sure you want your personal pypi on this? Otherwise LGTM.

**Comment by pselle** [comment]
Short of creating a separate pypi account just for this purpose, it seems
that's how it's done :/

On Jan 12, 2017 9:43 AM, "E Windisch" <notifications@github.com> wrote:

Sure you want your personal pypi on this? Otherwise LGTM.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iopipe/iopipe-python/pull/52#issuecomment-272180498>,
or mute the thread

**Comment by ewindisch** [comment]
Yep - could create a new account. _shrug_

**Pull request merged**
